// catch 블록을 비워 놓으면 예외는 무시된다 - 심히 의심스러운 코드!
try {
    ...
} catch (SomeException e) {
}
